"use client";

import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Phone, ShieldAlert, CreditCard, ExternalLink, Download, Check, X, Loader2, AlertCircle } from "lucide-react";
import { approveCandidatePayment, rejectCandidatePayment } from "@/app/(zone)/zone/actions";
import { toast } from "sonner";

interface CandidatePaymentData {
  id: string;
  nom: string;
  prenom: string;
  email: string;
  whatsapp: string | null;
  isActive: boolean | null;
  paymentStatus: "en_attente" | "en_cours" | "valide" | "rejete" | null;
  paymentId: string | null;
  paymentCaptureUrl: string | null;
  paymentNotes: string | null;
  paymentCreatedAt: Date | null;
  signedUrl?: string; // Signed URL generated by server
}

interface CaptureViewerProps {
  candidate: CandidatePaymentData | null;
  isOpen: boolean;
  onClose: () => void;
}

export default function CaptureViewer({ candidate, isOpen, onClose }: CaptureViewerProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showRejectForm, setShowRejectForm] = useState(false);
  const [rejectReason, setRejectReason] = useState("");

  if (!candidate) return null;

  const handleApprove = async () => {
    if (!candidate.paymentId) return;
    setIsSubmitting(true);
    try {
      const res = await approveCandidatePayment(candidate.paymentId, candidate.id);
      if (res.success) {
        toast.success(`Le paiement de ${candidate.prenom} ${candidate.nom} a été validé !`);
        onClose();
      } else {
        toast.error(res.error || "Une erreur est survenue lors de la validation.");
      }
    } catch {
      toast.error("Une erreur réseau est survenue.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!candidate.paymentId) return;
    if (!rejectReason.trim()) {
      toast.error("Veuillez saisir un motif pour le rejet.");
      return;
    }

    setIsSubmitting(true);
    try {
      const res = await rejectCandidatePayment(candidate.paymentId, rejectReason);
      if (res.success) {
        toast.success(`Le paiement de ${candidate.prenom} ${candidate.nom} a été rejeté.`);
        setShowRejectForm(false);
        setRejectReason("");
        onClose();
      } else {
        toast.error(res.error || "Une erreur est survenue lors du rejet.");
      }
    } catch {
      toast.error("Une erreur réseau est survenue.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const formatWhatsAppLink = (num: string | null) => {
    if (!num) return "";
    const cleanNum = num.replace(/\s+/g, "").replace("+", "");
    return `https://wa.me/${cleanNum}`;
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto bg-white p-6 rounded-2xl border border-slate-100 shadow-2xl">
        <DialogHeader className="border-b border-slate-100 pb-4">
          <DialogTitle className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <CreditCard className="w-5 h-5 text-[#D4A017]" />
            <span>Vérification du Reçu</span>
          </DialogTitle>
          <DialogDescription className="text-slate-500 font-medium mt-1">
            Candidat : <span className="font-bold text-slate-800">{candidate.prenom} {candidate.nom}</span> ({candidate.email})
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 py-4">
          {/* Left side: Info & actions */}
          <div className="space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="bg-slate-50 border border-slate-200/60 rounded-xl p-4 space-y-2 text-sm">
                <p className="text-slate-400 font-medium">WhatsApp Candidat</p>
                {candidate.whatsapp ? (
                  <a
                    href={formatWhatsAppLink(candidate.whatsapp)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-bold text-slate-800 hover:text-emerald-600 flex items-center gap-1 text-sm transition-colors"
                  >
                    <Phone className="w-3.5 h-3.5" />
                    <span>{candidate.whatsapp}</span>
                    <span className="text-xs bg-emerald-50 text-emerald-700 px-1.5 py-0.5 rounded ml-2 font-semibold">
                      Ouvrir WhatsApp
                    </span>
                  </a>
                ) : (
                  <p className="font-semibold text-slate-500 italic">Non renseigné</p>
                )}
              </div>

              <div className="bg-slate-50 border border-slate-200/60 rounded-xl p-4 space-y-2 text-sm">
                <p className="text-slate-400 font-medium">Statut Actuel</p>
                <div className="flex items-center gap-2">
                  {candidate.paymentStatus === "en_cours" && (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-50 text-amber-800 border border-amber-200">
                      En cours de vérification
                    </span>
                  )}
                  {candidate.paymentStatus === "valide" && (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200">
                      Validé & Actif
                    </span>
                  )}
                  {candidate.paymentStatus === "rejete" && (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-50 text-rose-800 border border-rose-200">
                      Rejeté
                    </span>
                  )}
                  {candidate.paymentStatus === "en_attente" && (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-50 text-slate-700 border border-slate-200">
                      Aucun reçu soumis
                    </span>
                  )}
                </div>
                {candidate.paymentNotes && candidate.paymentStatus === "rejete" && (
                  <p className="text-rose-700 font-medium mt-1 bg-rose-50/50 p-2 rounded border border-rose-100/50">
                    Motif : {candidate.paymentNotes}
                  </p>
                )}
              </div>
            </div>

            {/* Decisions Actions */}
            {!showRejectForm ? (
              <div className="space-y-3 pt-4 border-t border-slate-100">
                {candidate.paymentStatus === "en_cours" && (
                  <div className="flex flex-col sm:flex-row gap-3">
                    <button
                      onClick={handleApprove}
                      disabled={isSubmitting}
                      className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-sm py-2.5 px-4 rounded-xl flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                    >
                      {isSubmitting ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Check className="w-4 h-4" />
                      )}
                      <span>Approuver le reçu</span>
                    </button>
                    <button
                      onClick={() => setShowRejectForm(true)}
                      disabled={isSubmitting}
                      className="flex-1 bg-rose-50 hover:bg-rose-100 text-rose-600 border border-rose-200 font-bold text-sm py-2.5 px-4 rounded-xl flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                    >
                      <X className="w-4 h-4" />
                      <span>Rejeter le reçu</span>
                    </button>
                  </div>
                )}
                {candidate.paymentStatus === "valide" && (
                  <div className="bg-emerald-50 text-emerald-800 text-sm p-3 rounded-xl border border-emerald-150 flex items-start gap-2">
                    <Check className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                    <p className="font-medium">
                      Ce paiement a déjà été validé. Le compte du candidat est actif.
                    </p>
                  </div>
                )}
                 {candidate.paymentStatus === "rejete" && (
                  <div className="space-y-3">
                    <div className="bg-rose-50 text-rose-800 text-sm p-3 rounded-xl border border-rose-150 flex items-start gap-2">
                      <AlertCircle className="w-4 h-4 text-rose-600 flex-shrink-0 mt-0.5" />
                      <p className="font-medium">
                        Ce paiement a été rejeté. Le candidat doit soumettre un nouveau reçu.
                      </p>
                    </div>
                    <button
                      onClick={handleApprove}
                      disabled={isSubmitting}
                      className="w-full bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
                    >
                      {isSubmitting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" />}
                      <span>Valider malgré tout</span>
                    </button>
                  </div>
                )}
              </div>
            ) : (
              /* Rejection Reason Form */
              <form onSubmit={handleReject} className="space-y-3 pt-4 border-t border-slate-100 animate-fade-in">
                <div className="space-y-1">
                  <label htmlFor="reason" className="text-xs font-bold text-slate-700 block">
                    Motif du rejet (Sera envoyé par email au candidat) :
                  </label>
                  <textarea
                    id="reason"
                    required
                    placeholder="Ex: La capture d'écran est floue / Le montant indiqué ne correspond pas..."
                    value={rejectReason}
                    onChange={(e) => setRejectReason(e.target.value)}
                    className="w-full border border-slate-200 rounded-xl p-3 text-xs focus:outline-none focus:ring-2 focus:ring-rose-500 min-h-[80px] bg-slate-50"
                  />
                </div>
                <div className="flex gap-2">
                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="flex-1 bg-rose-600 hover:bg-rose-700 text-white font-bold text-xs py-2 px-4 rounded-xl flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
                  >
                    {isSubmitting ? (
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    ) : (
                      <X className="w-3.5 h-3.5" />
                    )}
                    <span>Confirmer le rejet</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setShowRejectForm(false);
                      setRejectReason("");
                    }}
                    className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-xs py-2 px-4 rounded-xl transition-colors"
                  >
                    Annuler
                  </button>
                </div>
              </form>
            )}
          </div>

          {/* Right side: Capture image display */}
          <div className="flex flex-col justify-between border border-slate-100 rounded-2xl p-4 bg-slate-50/50 min-h-[300px]">
            <p className="text-xs font-bold text-slate-700 mb-2">Capture d&apos;écran du reçu :</p>
            <div className="relative border border-slate-100 rounded-xl overflow-hidden bg-slate-100 flex-1 flex items-center justify-center max-h-[250px]">
              {candidate.signedUrl ? (
                <img
                  src={candidate.signedUrl}
                  alt={`Capture d&apos;écran de ${candidate.prenom} ${candidate.nom}`}
                  className="max-h-full max-w-full object-contain cursor-zoom-in"
                  onClick={() => window.open(candidate.signedUrl, "_blank")}
                />
              ) : (
                <div className="text-center p-6 text-slate-400 space-y-1">
                  <ShieldAlert className="w-8 h-8 mx-auto stroke-1" />
                  <p className="text-xs font-medium">Image non disponible</p>
                </div>
              )}
            </div>

            {candidate.signedUrl && (
              <div className="flex gap-2 mt-3">
                <a
                  href={candidate.signedUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1 bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 font-semibold text-xs py-2 rounded-xl flex items-center justify-center gap-1.5 transition-colors shadow-sm"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>Agrandir</span>
                </a>
                <a
                  href={candidate.signedUrl}
                  download={`Recu_OGE_${candidate.nom}_${candidate.prenom}.png`}
                  className="bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs py-2 px-3 rounded-xl flex items-center justify-center gap-1.5 transition-colors shadow-sm"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Télécharger</span>
                </a>
              </div>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
